import os


AWS_KEY = "ASIATQAU7PNLBFCDHVEB"
AWS_SECRET = "mpiShZjbNwMy5UFQZWTBTBnv6fxCnwGfRsqRTvVd"
AWS_SESSION = "FwoGZXIvYXdzEFkaDBHZ4zs6nBthKWM5CSLIAcjLLyvCko4QrUNNF1FQpHVlh7cUVSY+8tbVUZ2YEOTIicaZBU9OeVRHs6G8HVaonlIry/YiscwMrNOINcZLXVwtnnwfRnrijEuorTwjeJASe60MYFaRnoBWkIG67johqBvG5juxxDp4W9cIu80mipmEpI+pQE3uJTzvTNs/7rk4chfsVo4GIQ4gMgVDBk02khLGdu5yetB+uZr7mzX0YxL8HaGa6/QxEev+PrmWJ29EMvj9BqAfS+oEf+zWknHnzyDKTLM3MsgDKK3LjIcGMi3kL2sQH6cyVt0kYCHvXgxSmlEC0ZKkG4RSKYoSJQSw2SqhlRwYUdVevm8fPRE="
S3_BUCKET = "gardenia"
SECRET_KEY = os.urandom(32)
DEBUG = False
PORT = 5000
